### ISSUE TITLE
Update gemfile dependencies

### ISSUE THREAD

**Issue by brian-griffin** [collective-logic/collective-logic.github.io#7]
Need to update ffi, jekyll and rubyzip

![screen shot 2018-10-11 at 10 33 24](https://user-images.githubusercontent.com/1629482/46795098-2d37cc80-cd41-11e8-963f-707cc78c67a7.png)

See https://github.com/collective-logic/collective-logic.github.io/network/dependencies for details

**Comment by sterowney** [comment]
Closing as this was updated
